import 'package:flutter/material.dart';
import 'package:flutterapp/pontoapp/generatedesqueciminhasenhawidget1/generated/GeneratedLOGINWidget1.dart';
import 'package:flutterapp/pontoapp/generatedesqueciminhasenhawidget1/generated/GeneratedGroup8Widget1.dart';
import 'package:flutterapp/pontoapp/generatedesqueciminhasenhawidget1/generated/GeneratedGroup6Widget2.dart';
import 'package:flutterapp/pontoapp/generatedesqueciminhasenhawidget1/generated/GeneratedArrowLeftWidget6.dart';
import 'package:flutterapp/pontoapp/generatedesqueciminhasenhawidget1/generated/GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo2.dart';
import 'package:flutterapp/pontoapp/generatedesqueciminhasenhawidget1/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/pontoapp/generatedesqueciminhasenhawidget1/generated/GeneratedGroup7Widget1.dart';

/* Frame Esqueci minha senha
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEsqueciminhasenhaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 62.0,
                child: GeneratedGroup3Widget1(),
              ),
              Positioned(
                left: 37.0,
                top: 404.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 62.0,
                child: GeneratedGroup7Widget1(),
              ),
              Positioned(
                left: 37.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 56.0,
                child: GeneratedGroup6Widget2(),
              ),
              Positioned(
                left: 37.0,
                top: 493.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 56.0,
                child: GeneratedGroup8Widget1(),
              ),
              Positioned(
                left: 114.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 63.0,
                child: GeneratedLOGINWidget1(),
              ),
              Positioned(
                left: 9.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 56.0,
                child:
                    GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo2(),
              ),
              Positioned(
                left: 318.0,
                top: 8.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedArrowLeftWidget6(),
              )
            ]),
      ),
    ));
  }
}
