import 'package:flutter/material.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedTerminodeJornada1800Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedRetornodoalmooWidget.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedArrowLeftWidget10.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedIniciosdeJornadaas0800Widget.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedMarcarPontoWidget.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedRectangle32Widget.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedSaidaparaoalmooWidget.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedMarcaodePontoWidget2.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedEllipse2Widget.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/pontoapp/generatedmarcaodepontowidget1/generated/GeneratedEllipse3Widget.dart';

/* Frame Marcação de Ponto 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMarcaodePontoWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 79.0,
                child: GeneratedRectangle31Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 296.0,
                height: 41.0,
                child: GeneratedMarcaodePontoWidget2(),
              ),
              Positioned(
                left: 50.0,
                top: 143.0,
                right: null,
                bottom: null,
                width: 258.0,
                height: 176.0,
                child: GeneratedRectangle32Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 215.0,
                height: 41.0,
                child: TransformHelper.translate(
                    x: -8.00,
                    y: -108.00,
                    z: 0,
                    child: GeneratedMarcarPontoWidget()),
              ),
              Positioned(
                left: 18.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 56.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 31.0,
                child: GeneratedIniciosdeJornadaas0800Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 438.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 29.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 31.0,
                child: GeneratedSaidaparaoalmooWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 25.0,
                height: 29.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 233.0,
                height: 31.0,
                child: GeneratedRetornodoalmooWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 31.0,
                child: GeneratedTerminodeJornada1800Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 18.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedArrowLeftWidget10(),
              )
            ]),
      ),
    ));
  }
}
