import 'package:flutter/material.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedSaidaalmooWidget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedArrowLeftWidget8.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine18Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine20Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedRectangle23Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine13Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine17Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedMatrculaWidget1.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedCorreodoPontoWidget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedGroup12Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine19Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine14Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedDataWidget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/pontoapp/generatedcorreodopontowidget/generated/GeneratedHorariosWidget.dart';

/* Frame Correção do ponto 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCorreodopontoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 389.0,
      height: 647.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 389.0,
              height: 70.0,
              child: GeneratedRectangle22Widget(),
            ),
            Positioned(
              left: 86.0,
              top: 15.0,
              right: null,
              bottom: null,
              width: 287.0,
              height: 41.0,
              child: GeneratedCorreodoPontoWidget(),
            ),
            Positioned(
              left: 15.0,
              top: 122.0,
              right: null,
              bottom: null,
              width: 344.0,
              height: 50.0,
              child: GeneratedRectangle23Widget(),
            ),
            Positioned(
              left: 134.0,
              top: 133.0,
              right: null,
              bottom: null,
              width: 110.0,
              height: 34.0,
              child: GeneratedMatrculaWidget1(),
            ),
            Positioned(
              left: 0.0,
              top: 235.0,
              right: null,
              bottom: null,
              width: 751.0,
              height: 370.0,
              child: GeneratedGroup12Widget(),
            ),
            Positioned(
              left: 15.0,
              top: 245.0,
              right: null,
              bottom: null,
              width: 63.0,
              height: 37.0,
              child: GeneratedDataWidget(),
            ),
            Positioned(
              left: 86.0,
              top: 247.0,
              right: null,
              bottom: null,
              width: 98.0,
              height: 34.0,
              child: GeneratedHorariosWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 290.0,
              right: null,
              bottom: null,
              width: 5.0,
              height: 1.0,
              child: GeneratedLine7Widget(),
            ),
            Positioned(
              left: 187.0,
              top: 245.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 1.0,
              child: GeneratedLine8Widget(),
            ),
            Positioned(
              left: 285.0,
              top: 230.0,
              right: null,
              bottom: null,
              width: 375.0213317871094,
              height: 1.0,
              child: GeneratedLine10Widget(),
            ),
            Positioned(
              left: 73.0,
              top: 240.0,
              right: null,
              bottom: null,
              width: 365.0,
              height: 1.0,
              child: GeneratedLine12Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 291.0,
              right: null,
              bottom: null,
              width: 751.0059814453125,
              height: 1.0,
              child: GeneratedLine14Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 351.0,
              right: null,
              bottom: null,
              width: 751.0006713867188,
              height: 1.0,
              child: GeneratedLine15Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 416.0,
              right: null,
              bottom: null,
              width: 751.002685546875,
              height: 1.0,
              child: GeneratedLine16Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 465.0,
              right: null,
              bottom: null,
              width: 751.0166625976562,
              height: 1.0,
              child: GeneratedLine17Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 514.0,
              right: null,
              bottom: null,
              width: 751.002685546875,
              height: 1.0,
              child: GeneratedLine18Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 539.0,
              right: null,
              bottom: null,
              width: 1.0,
              height: 1.0,
              child: GeneratedLine19Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 555.0,
              right: null,
              bottom: null,
              width: 751.0006713867188,
              height: 1.0,
              child: GeneratedLine20Widget(),
            ),
            Positioned(
              left: 15.0,
              top: 13.0,
              right: null,
              bottom: null,
              width: 41.0,
              height: 41.0,
              child: GeneratedArrowLeftWidget8(),
            ),
            Positioned(
              left: 452.0,
              top: 240.0,
              right: null,
              bottom: null,
              width: 373.0,
              height: 1.0,
              child: GeneratedLine13Widget(),
            ),
            Positioned(
              left: 302.0,
              top: 248.0,
              right: null,
              bottom: null,
              width: 152.0,
              height: 31.0,
              child: GeneratedSaidaalmooWidget(),
            )
          ]),
    ));
  }
}
