import 'package:flutter/material.dart';

/* Vector Rectangle 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 60.0,
      height: 23.0,
    ));
  }
}
