import 'package:flutter/material.dart';
import 'package:flutterapp/ponto1app/generatedesqueciminhasenhawidget2/generated/GeneratedGroup3Widget2.dart';
import 'package:flutterapp/ponto1app/generatedesqueciminhasenhawidget2/generated/GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo3.dart';
import 'package:flutterapp/ponto1app/generatedesqueciminhasenhawidget2/generated/GeneratedGroup8Widget2.dart';
import 'package:flutterapp/ponto1app/generatedesqueciminhasenhawidget2/generated/GeneratedArrow3Widget.dart';
import 'package:flutterapp/ponto1app/generatedesqueciminhasenhawidget2/generated/GeneratedEsqueciminhaSenhaWidget.dart';
import 'package:flutterapp/ponto1app/generatedesqueciminhasenhawidget2/generated/GeneratedGroup7Widget2.dart';
import 'package:flutterapp/ponto1app/generatedesqueciminhasenhawidget2/generated/GeneratedArrow2Widget.dart';

/* Frame Esqueci minha senha
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEsqueciminhasenhaWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 37.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 62.0,
                child: GeneratedGroup3Widget2(),
              ),
              Positioned(
                left: 35.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 62.0,
                child: GeneratedGroup7Widget2(),
              ),
              Positioned(
                left: 37.0,
                top: 399.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 56.0,
                child: GeneratedGroup8Widget2(),
              ),
              Positioned(
                left: 45.0,
                top: 14.0,
                right: null,
                bottom: null,
                width: 446.0,
                height: 41.0,
                child: GeneratedEsqueciminhaSenhaWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 7.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 53.0,
                child:
                    GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo3(),
              ),
              Positioned(
                left: 51.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 368.8956604003906,
                height: 0.0,
                child: GeneratedArrow2Widget(),
              ),
              Positioned(
                left: 91.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 434.8850402832031,
                height: 0.0,
                child: GeneratedArrow3Widget(),
              )
            ]),
      ),
    ));
  }
}
