import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Line 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLine11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: -0.01,
            b: -1.00,
            c: 1.00,
            d: -0.01,
            child: Container(
              width: 379.0118713378906,
              height: 0.0,
              child: SvgWidget(painters: [
                SvgPathPainter.stroke(
                  1.0,
                  strokeJoin: StrokeJoin.miter,
                )
                  ..addPath(
                      'M-1.42109e-14 0.5L379.012 0.5L379.012 -0.5L-1.42109e-14 -0.5L-1.42109e-14 0.5Z')
                  ..color = Color.fromARGB(255, 0, 0, 0),
              ]),
            )));
  }
}
