import 'package:flutter/material.dart';
import 'package:flutterapp/pontoapp/generatedtelainicialwidget/generated/GeneratedTelainicialWidget1.dart';
import 'package:flutterapp/pontoapp/generatedtelainicialwidget/generated/GeneratedGroup11Widget.dart';
import 'package:flutterapp/pontoapp/generatedtelainicialwidget/generated/GeneratedCadastroWidget.dart';
import 'package:flutterapp/pontoapp/generatedtelainicialwidget/generated/GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo4.dart';
import 'package:flutterapp/pontoapp/generatedtelainicialwidget/generated/GeneratedRectangle33Widget.dart';
import 'package:flutterapp/pontoapp/generatedtelainicialwidget/generated/GeneratedGearFillWidget.dart';
import 'package:flutterapp/pontoapp/generatedtelainicialwidget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/pontoapp/generatedtelainicialwidget/generated/GeneratedRectangle34Widget.dart';
import 'package:flutterapp/pontoapp/generatedtelainicialwidget/generated/GeneratedRectangle18Widget.dart';
import 'package:flutterapp/pontoapp/generatedtelainicialwidget/generated/GeneratedMarcaodePontoWidget.dart';

/* Frame Tela inicial
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTelainicialWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 368.0,
        height: 647.0,
        decoration: BoxDecoration(
          border: Border.all(
            width: 1.0,
            color: Color.fromARGB(255, 0, 0, 0),
          ),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 368.0,
                height: 69.0,
                child: GeneratedRectangle18Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 43.0,
                child: GeneratedTelainicialWidget1(),
              ),
              Positioned(
                left: 189.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 126.0,
                child: GeneratedGroup11Widget(),
              ),
              Positioned(
                left: 1575.0,
                top: -158.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 117.0,
                child: GeneratedRectangle20Widget(),
              ),
              Positioned(
                left: 314.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 37.0,
                height: 37.0,
                child: GeneratedGearFillWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 126.0,
                child: GeneratedRectangle33Widget(),
              ),
              Positioned(
                left: 55.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 29.0,
                child: GeneratedCadastroWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 303.0,
                height: 146.0,
                child: GeneratedRectangle34Widget(),
              ),
              Positioned(
                left: 90.0,
                top: 274.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 26.0,
                child: GeneratedMarcaodePontoWidget(),
              ),
              Positioned(
                left: 117.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 121.0,
                child:
                    GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo4(),
              )
            ]),
      ),
    ));
  }
}
