import 'package:flutter/material.dart';
import 'package:flutterapp/ponto1app/generatedtelainicialwidget2/generated/GeneratedGroup1Widget2.dart';
import 'package:flutterapp/ponto1app/generatedtelainicialwidget2/generated/GeneratedGroup2Widget.dart';
import 'package:flutterapp/ponto1app/generatedtelainicialwidget2/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/ponto1app/generatedtelainicialwidget2/generated/GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo5.dart';
import 'package:flutterapp/ponto1app/generatedtelainicialwidget2/generated/GeneratedDesenvolvedoresWidget1.dart';
import 'package:flutterapp/ponto1app/generatedtelainicialwidget2/generated/GeneratedArrowLeftWidget6.dart';

/* Frame Tela inicial
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTelainicialWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 49.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 56.0,
                child: GeneratedGroup1Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 56.0,
                child: GeneratedGroup2Widget(),
              ),
              Positioned(
                left: 261.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 145.0,
                child:
                    GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo5(),
              ),
              Positioned(
                left: 65.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 241.0,
                height: 55.0,
                child: GeneratedRectangle35Widget(),
              ),
              Positioned(
                left: 88.0,
                top: 551.0,
                right: null,
                bottom: null,
                width: 201.0,
                height: 34.0,
                child: GeneratedDesenvolvedoresWidget1(),
              ),
              Positioned(
                left: 8.0,
                top: 13.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedArrowLeftWidget6(),
              )
            ]),
      ),
    ));
  }
}
