import 'package:flutter/material.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedArrowLeftWidget3.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedNomeWidget1.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedSetorWidget.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedDatadeAdmissaoWidget.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedMatriculaWidget.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedCargoWidget.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedCadastroWidget2.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/ponto1app/generatedcadastrowidget1/generated/GeneratedRectangle28Widget.dart';

/* Frame Cadastro 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastroWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: -7.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 87.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 44.0,
                child: GeneratedCadastroWidget2(),
              ),
              Positioned(
                left: 132.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 95.0,
                height: 44.0,
                child: GeneratedNomeWidget1(),
              ),
              Positioned(
                left: 22.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 56.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 118.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 145.0,
                height: 44.0,
                child: GeneratedMatriculaWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 52.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 149.0,
                top: 347.0,
                right: null,
                bottom: null,
                width: 97.0,
                height: 44.0,
                child: GeneratedCargoWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 51.0,
                child: GeneratedRectangle29Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 449.0,
                right: null,
                bottom: null,
                width: 87.0,
                height: 44.0,
                child: GeneratedSetorWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 538.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 55.0,
                child: GeneratedRectangle30Widget(),
              ),
              Positioned(
                left: 61.0,
                top: 544.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 41.0,
                child: GeneratedDatadeAdmissaoWidget(),
              ),
              Positioned(
                left: 20.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedArrowLeftWidget3(),
              ),
              Positioned(
                left: 33.0,
                top: 135.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 55.0,
                child: GeneratedRectangle26Widget(),
              )
            ]),
      ),
    ));
  }
}
