import 'package:flutter/material.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo1.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedRectangle16Widget.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedGroup7Widget.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedGroup6Widget1.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedGroup8Widget.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedOuWidget1.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedRegistrarWidget2.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedNomeWidget.dart';
import 'package:flutterapp/ponto1app/generatedregistrarwidget/generated/GeneratedArrowLeftWidget1.dart';

/* Frame Registrar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRegistrarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1356.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 401.0,
                      height: 987.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 407.0,
                              right: null,
                              bottom: null,
                              width: 302.0,
                              height: 62.0,
                              child: GeneratedGroup7Widget(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 494.0,
                              right: null,
                              bottom: null,
                              width: 302.0,
                              height: 62.0,
                              child: GeneratedGroup8Widget(),
                            ),
                            Positioned(
                              left: 48.0,
                              top: 598.0,
                              right: null,
                              bottom: null,
                              width: 302.0,
                              height: 62.0,
                              child: GeneratedGroup9Widget(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 917.0,
                              right: null,
                              bottom: null,
                              width: 298.0,
                              height: 56.0,
                              child: GeneratedGroup6Widget1(),
                            ),
                            Positioned(
                              left: 280.0,
                              top: 1322.0,
                              right: null,
                              bottom: null,
                              width: 34.0,
                              height: 34.0,
                              child: GeneratedOuWidget1(),
                            ),
                            Positioned(
                              left: 90.0,
                              top: 129.0,
                              right: null,
                              bottom: null,
                              width: 210.0,
                              height: 63.0,
                              child: GeneratedRegistrarWidget2(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 313.0,
                              right: null,
                              bottom: null,
                              width: 302.0,
                              height: 62.0,
                              child: GeneratedGroup5Widget(),
                            ),
                            Positioned(
                              left: 43.0,
                              top: 218.0,
                              right: null,
                              bottom: null,
                              width: 311.0,
                              height: 63.0,
                              child: GeneratedRectangle16Widget(),
                            ),
                            Positioned(
                              left: 147.0,
                              top: 226.0,
                              right: null,
                              bottom: null,
                              width: 73.0,
                              height: 34.0,
                              child: GeneratedNomeWidget(),
                            ),
                            Positioned(
                              left: 141.0,
                              top: 8.0,
                              right: null,
                              bottom: null,
                              width: 133.0,
                              height: 121.0,
                              child:
                                  GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo1(),
                            ),
                            Positioned(
                              left: 50.0,
                              top: 773.0,
                              right: null,
                              bottom: null,
                              width: 302.0,
                              height: 56.0,
                              child: GeneratedGroup1Widget1(),
                            ),
                            Positioned(
                              left: 9.0,
                              top: 8.0,
                              right: null,
                              bottom: null,
                              width: 41.0,
                              height: 41.0,
                              child: GeneratedArrowLeftWidget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
