import 'package:flutter/material.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedArrowLeftWidget.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedArrowLeftWidget1.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedLOGINWidget.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedEsqueciminhasenhaWidget.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/pontoapp/generatedloginwidget/generated/GeneratedOuWidget.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 667.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 31.0,
                top: 197.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 62.0,
                child: GeneratedGroup3Widget(),
              ),
              Positioned(
                left: 31.0,
                top: 293.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 62.0,
                child: GeneratedGroup4Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 123.0,
                right: null,
                bottom: null,
                width: 152.0,
                height: 63.0,
                child: GeneratedLOGINWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 56.0,
                child: GeneratedGroup1Widget(),
              ),
              Positioned(
                left: 36.0,
                top: 392.0,
                right: null,
                bottom: null,
                width: 302.0,
                height: 56.0,
                child: GeneratedGroup6Widget(),
              ),
              Positioned(
                left: 179.0,
                top: 500.0,
                right: null,
                bottom: null,
                width: 34.0,
                height: 34.0,
                child: GeneratedOuWidget(),
              ),
              Positioned(
                left: 179.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 21.0,
                child: GeneratedEsqueciminhasenhaWidget(),
              ),
              Positioned(
                left: 203.0,
                top: 465.0,
                right: null,
                bottom: null,
                width: 150.00332641601562,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 171.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 193.0,
                height: 20.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 127.0,
                top: 12.0,
                right: null,
                bottom: null,
                width: 133.0,
                height: 121.0,
                child:
                    GeneratedD4f3bf198edca09ba9664f6732595b6bexecutivocomiconederelo(),
              ),
              Positioned(
                left: 10.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedArrowLeftWidget(),
              ),
              Positioned(
                left: 10.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 41.0,
                height: 41.0,
                child: GeneratedArrowLeftWidget1(),
              )
            ]),
      ),
    ));
  }
}
