import 'package:flutter/material.dart';
import 'package:flutterapp/ponto1app/generatedapresentaowidget/generated/Generated4ADSNoiteWidget1.dart';
import 'package:flutterapp/ponto1app/generatedapresentaowidget/generated/GeneratedApresentaoWidget1.dart';
import 'package:flutterapp/ponto1app/generatedapresentaowidget/generated/GeneratedAplicativoparamarcaodepontoecontroledehorastrabalhadasp.dart';
import 'package:flutterapp/ponto1app/generatedapresentaowidget/generated/GeneratedAlineMendesWidget.dart';
import 'package:flutterapp/ponto1app/generatedapresentaowidget/generated/GeneratedArrowLeftWidget5.dart';
import 'package:flutterapp/ponto1app/generatedapresentaowidget/generated/GeneratedCiroAnphyloWidget.dart';
import 'package:flutterapp/ponto1app/generatedapresentaowidget/generated/GeneratedDesenvolvedoresWidget.dart';
import 'package:flutterapp/ponto1app/generatedapresentaowidget/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/ponto1app/generatedapresentaowidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/ponto1app/generatedapresentaowidget/generated/Generated4ADSNoiteWidget.dart';

/* Frame Apresentação 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedApresentaoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 667.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 96.61363983154297,
              top: 86.1022720336914,
              right: null,
              bottom: null,
              width: 155.53977966308594,
              height: 23.011363983154297,
              child: GeneratedApresentaoWidget1(),
            ),
            Positioned(
              left: 0.6136363744735718,
              top: 166.0,
              right: null,
              bottom: null,
              width: 320.7975769042969,
              height: 134.30682373046875,
              child:
                  GeneratedAplicativoparamarcaodepontoecontroledehorastrabalhadasp(),
            ),
            Positioned(
              left: 64.0,
              top: 334.0,
              right: null,
              bottom: null,
              width: 198.0,
              height: 31.0,
              child: GeneratedDesenvolvedoresWidget(),
            ),
            Positioned(
              left: 47.0,
              top: 382.0,
              right: null,
              bottom: null,
              width: 76.0,
              height: 101.0,
              child: GeneratedImage1Widget(),
            ),
            Positioned(
              left: 220.0,
              top: 382.0,
              right: null,
              bottom: null,
              width: 83.0,
              height: 97.0,
              child: GeneratedImage2Widget(),
            ),
            Positioned(
              left: 8.0,
              top: 515.0,
              right: null,
              bottom: null,
              width: 156.0,
              height: 31.0,
              child: GeneratedAlineMendesWidget(),
            ),
            Positioned(
              left: 189.0,
              top: 515.0,
              right: null,
              bottom: null,
              width: 147.0,
              height: 31.0,
              child: GeneratedCiroAnphyloWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 568.0,
              right: null,
              bottom: null,
              width: 134.0,
              height: 31.0,
              child: Generated4ADSNoiteWidget(),
            ),
            Positioned(
              left: 194.0,
              top: 568.0,
              right: null,
              bottom: null,
              width: 134.0,
              height: 31.0,
              child: Generated4ADSNoiteWidget1(),
            ),
            Positioned(
              left: 8.0,
              top: 11.0,
              right: null,
              bottom: null,
              width: 41.0,
              height: 32.0,
              child: GeneratedArrowLeftWidget5(),
            )
          ]),
    ));
  }
}
